### ISSUE TITLE
Dropdown not working in Mobile Site

### ISSUE THREAD

**Issue by thandaanda** [mizzao/meteor-bootstrap-3#10]
Bootstrap collapsed menu not working in mobile.

http://stackoverflow.com/questions/17435359/bootstrap-collapsed-menu-links-not-working-on-mobile-devices/17440942#17440942

**Comment by mizzao** [comment]
We're just wrapping Bootstrap. Please report all problems with Bootstrap itself over in their repo: https://github.com/twbs/bootstrap
