### ISSUE TITLE
media queries

### ISSUE THREAD

**Issue by sangyoo91** [mizzao/meteor-bootstrap-3#13]
Hi.

I've just deployed my meteor app to test on meteor.com.

I've noticed that if I browse to the deploy.meteor.com on my phone, the media queries would not work. It would just show a zoomed out version of a computer screen.

I was wondering why this is, and that if it is a meteor-bootstrap-3 problem.

The responsive css media queries work fine when loaded in computer browsers

**Comment by mizzao** [comment]
Can you clarify what you mean by "media queries"?

**Comment by simison** [comment]
Do you have this at your header;

``` html
 <meta name="viewport" content="width=device-width, initial-scale=1">
```

http://getbootstrap.com/getting-started/#template

**Comment by sangyoo91** [comment]
thank you. I thought the package would automatically include that

**Comment by mizzao** [comment]
Hey @simison, is that something that would make sense to include in the package, or is it different per device?

Even if different per device, might make sense for Meteor to detect the client type (including Cordova clients) and include the appropriate tag automatically.

**Comment by simison** [comment]
@mizzao No it's better to leave it up to developers. Sometimes people specifically don't want to use responsiveness.

Depending on your setup, you might want to have different content of for viewport. Eg. target Androids, have custom fixed width or target IE quirks mode.

You could of course mention it at the readme or just link to http://getbootstrap.com/getting-started/#template

Same goes with IE support shim scripts, less opinionated this package the better.

Cheers!
