### ISSUE TITLE
Direct integration, similar to d3, with tests

### ISSUE THREAD

**Issue by dandv** [mizzao/meteor-bootstrap-3#14]
Since you've been shepherding this for quite a while, might you take a look at my stab at a [direct integration](https://github.com/raix/Meteor-community-discussions/issues/14)?

https://github.com/dandv/bootstrap/compare/meteor-integration

Tests run _mostly_ ok, though I'm not sure why only some JS works (see [the README](https://github.com/dandv/bootstrap/tree/meteor-integration/meteor)).

Would be great if we could get the Bootstrap folks to pull in a solid PR.

**Comment by mizzao** [comment]
I'm happy to do this and reduce the maintaining load. However, I recently took this over from @yasinuslu and I'm definitely not as familiar with hooking into other packages' build process like you - so you should feel free to take a stab if you're in the mood.

I think this entire process would be much better served with having package renaming, including author/organization - that would streamline the migration a lot better and maintain continuity for existing installs. @ekatek, any updates on when that will be possible?

**Comment by dandv** [comment]
In the meantime I've [hooked into Bootstrap's Gruntfile](https://github.com/dandv/bootstrap/compare/meteor-integration#diff-1) so the maintenance load could be effectively zero.

We're live at http://atmospherejs.com/twbs/bootstrap

Waiting for any final feedback/thoughts before submitting the PR.

**Comment by dandv** [comment]
[Engaged with the Bootstrap team.](https://github.com/twbs/bootstrap/pull/15376)

**Comment by mizzao** [comment]
Thanks for your work on this. I've been busy with some other stuff lately but will hopefully have a chance to pitch in over the holidays.

**Comment by mizzao** [comment]
Hey @dandv, is it safe to set this package as unmigrated now and recommend that people switch to `twbs:bootstrap` instead?

**Comment by dandv** [comment]
Yes, I do believe so. I've battle-tested it from apps and other packages, e.g. @FezVrasta's Material Design Theme, and it's been through several rounds of feedback from the Bootstrap folks.

**Comment by mizzao** [comment]
OK, unmigrated and README updated. Good luck to `twbs:bootstrap`, you should see a ton of users switch over soon.

**Comment by dandv** [comment]
:bow: & :+1: 

https://atmospherejs.com/?q=bootstrap still shows it though?

Maybe related to https://github.com/percolatestudio/atmosphere/issues/320 ?

**Comment by mizzao** [comment]
I don't know if atmosphere looks for unmigrated. I'd be surprised if it does.

**Comment by dandv** [comment]
[Umigrated packages should not get auto-flagged and not show up in search results.](https://github.com/percolatestudio/atmosphere/issues/308). CC @tmeasday, @dominicnguyen.

**Comment by tmeasday** [comment]
Looks good now, no?
