### ISSUE TITLE
Remove CSS url overrides

### ISSUE THREAD

**Issue by mizzao** [mizzao/meteor-bootstrap-3#15]
@dandv and @gadicc mention that it is no longer a problem after Meteor 0.8.1.2 and later.

(Sorry for the spam; currently traveling and wanted to note this for later.)

**Comment by gadicc** [comment]
All good.  So all the refs are in one place (might help others too):

>  I had to look into this a bit.  Meteor will automatically "convert relative URLs to absolute URLs when merging CSS files" [since v0.8.1](https://github.com/meteor/meteor/blob/b96c5d7962a9e59b9efaeb93eb81020e0548e378/History.md#v081) - I had totally missed the memo on this one.  In [packages/minifiers](https://github.com/meteor/meteor/blob/180586a115a24de1e4a0068c3a784a678c691539/packages/minifiers/minifiers.js#L80-L134).  Also seems the initial implementation was [buggy](https://github.com/meteor/meteor/issues/2106) until [v0.8.1.2](https://github.com/meteor/meteor/commit/1e4838ccd38c2df142591a67d675ac38eb8a5630#diff-6672a42c081905759a265ce05f6f6596) (but wasn't mentioned in History.md).
> 
> So basically any kind of `path-override.css` is only needed for < 0.8.1.2 compatibility, so not necessary on anything published to Meteor Package Server (which is 0.9+, of course).
