### ISSUE TITLE
unmigrate the mrt package

### ISSUE THREAD

**Issue by dandv** [mizzao/meteor-bootstrap-3#16]
https://atmospherejs.com/mrt/bootstrap-3 still shows up in searches for "bootstrap".

@tmeasday would [suggest](https://github.com/stefanocudini/leaflet-search/issues/55#issuecomment-93108533) `mrt admin set-unmigrated mrt:bootstrap-3`.

**Comment by mizzao** [comment]
I received the (expected) response:

```
Error from package server: You are not an authorized maintainer for this package. [401] 
```

**Comment by dandv** [comment]
@tmeasday: any way to unmigrate this one?

**Comment by tmeasday** [comment]
@mizzao do you want to be a maintainer? Or do you just want me to unmigrate it?
