### ISSUE TITLE
No glyphicons on Firefox with Meteor 9.2.1

### ISSUE THREAD

**Issue by zapaz** [mizzao/meteor-bootstrap-3#3]
On a Mac OSX configuration Bootstrap glyphicons are not displayed on Firefox with 9.2.1 (small numbers instead)

But they are displayed with other browser (Chrome and Safari Mac OSX) or with previous Meteor version 9.1.1

Also got the problem on Safari iOS

see https://github.com/meteor/meteor/issues/2608

**Comment by mizzao** [comment]
I think this is what was proposed in #2, will take a look soon.

**Comment by mizzao** [comment]
Bootstrap tries to load the symbols using a font if possible, otherwise it falls back to images. That may be why it works in some browsers and not others, because of the asset path change in meteor/meteor#2580.

I just merged #2, will publish the fixed version soon.

**Comment by evolross** [comment]
I'm getting this error too in Firefox 32.0.3.  IE 11.0 and Chrome glyphicons work fine.  Just an FYI, I know you're working on it.

**Comment by mizzao** [comment]
I've published version `3.2.0_1` which you can install on 0.9.3 or later. Could you please update to that version, and let me know if you still have the problem?

**Comment by boustanihani** [comment]
@mizzao what changes were made since 3.2.0 ?? When I look at the commits I only see the version number changing but no other files: https://github.com/mizzao/meteor-bootstrap-3/commit/ad8c37c7bc2c9922656962189fe84d1305961972

**Comment by zapaz** [comment]
thanks, works fine in Firefox wih 3.2.0_1

**Comment by mizzao** [comment]
@boustanihani It was already fixed in previous commits, just not published: https://github.com/mizzao/meteor-bootstrap-3/compare/v3.2.0...v3.2.0_1

**Comment by boustanihani** [comment]
Thanks for the feedback :)
