### ISSUE TITLE
Tooltips and Popovers Not Working.

### ISSUE THREAD

**Issue by evolross** [mizzao/meteor-bootstrap-3#4]
If I cut and paste this example button from <code>http://getbootstrap.com/javascript/#tooltips</code>

```
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="right" title="Tooltip on right">Tooltip on right</button>
```

The tooltip doesn't work.  Same with popover examples.

I'm using the latest Firefox and Meteor 0.9.2.  Other things like tab-panes and modals work fine.

**Comment by evolross** [comment]
Whoops, I wasn't initializing them. For anyone who finds them not working, in your <code>Template.someTemplate.rendered</code> add <code>$('element').tooltip();</code>.  My bad.

**Comment by dandv** [comment]
[The official twbs:bootstrap package](atmospherejs.com/twbs/bootstrap) does the initialization for you.
