### ISSUE TITLE
Where are the files to make update.sh work?

### ISSUE THREAD

**Issue by ssteinerx** [mizzao/meteor-bootstrap-3#6]
Trying to update the package for local use to Bootstrap bleeding edge checkout but the update.sh file seems to not be within a directory structure that allows it to run...

Thanks,

Steve

**Comment by mizzao** [comment]
We should ask @yasinuslu; I didn't create that file originally.

**Comment by ssteinerx** [comment]
I've emailed him.  Thanks for the reply!

Steve

**Comment by yasinuslu** [comment]
Thanks for asking, i'll have a look right now.

**Comment by yasinuslu** [comment]
I have updated update.sh and created this PR #7 You need to have grunt-cli and npm installed for script to work.

I don't want to pollute search results for `bootstrap-3` so i haven't published the package to meteor.

**Comment by ssteinerx** [comment]
Awesome, thank you!

Steve

**Comment by mizzao** [comment]
Tested the new `update.sh` and it works.

Make sure you `npm install -g grunt-cli`.

**Comment by ssteinerx** [comment]
I've already upgraded to the new version and confirmed that it works.  Also, showed me how the original was built which is what I was after.

Thanks for your help with this!

Steve
