### ISSUE TITLE
New version (3.3.0)

### ISSUE THREAD

**Issue by lumatijev** [mizzao/meteor-bootstrap-3#8]
Can you please update package to new version of Bootstrap? Thank you in advance.

**Comment by delgermurun** [comment]
:+1:

**Comment by boustanihani** [comment]
:+1:

**Comment by mizzao** [comment]
`3.3.0` is out and published. Give it a try?

Hey @yasinuslu, what do you do with the `.css.map` files? Do you know if Meteor can use them? I know it uses source maps for stuff like coffeescript, but what about CSS?

**Comment by yasinuslu** [comment]
@mizzao I didn't see any `.css.map` file in the package ? We shouldn't need source maps since we're not packaging less or other preprocessor files.

**Comment by mizzao** [comment]
Well, there were some `.css.map` files copied over by the update script that weren't in `.gitignore`, so I was wondering what you had done with them before. I guess you just hadn't added them. The `bootstrap-theme.css` has been added, but isn't actually used in the package.

**Comment by yasinuslu** [comment]
Script just copies everything in bootstrap folder. I haven't look closely for which extra files are in it :)
